workload ={   -1: {   'equation': 'input',
            'loop_dim_size': {'B': 1, 'G': 1, 'OY': 256, 'OX': 256},
            'precision': 8,
            'core_allocation': 1,
            'memory_operand_links': {'O': 'I1'}},
    0: {   'operator_type': 'dw_Conv',
           'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'G': 56, 'OY': 256, 'OX': 256, 'FY': 5, 'FX': 5},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [-1]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_0_PART_0_0_fuse_bias_add_Conv_0_1'},
    1: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 12, 'C': 56, 'OY': 256, 'OX': 256, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [0]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_2_PART_0_3_fuse_bias_add_Conv_2_4'},
    2: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 12, 'C': 12, 'OY': 256, 'OX': 256, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [1]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_4_PART_0_6_fuse_bias_add_Conv_4_7'},
    3: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 12, 'C': 12, 'OY': 256, 'OX': 256, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [2]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_6_PART_0_9_fuse_bias_add_Conv_6_10'},
    4: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 12, 'C': 12, 'OY': 256, 'OX': 256, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [3]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_8_PART_0_12_fuse_bias_add_Conv_8_13'},
    5: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 12, 'C': 12, 'OY': 256, 'OX': 256, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [4]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_10_PART_0_15_fuse_bias_add_Conv_10_16'},
    6: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 56, 'C': 12, 'OY': 256, 'OX': 256, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [5]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_12_PART_0_18_fuse_bias_add_Conv_12_19'},
    7: {   'operator_type': 'Conv_from_deconv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 1, 'C': 56, 'OY': 256, 'OX': 256, 'FY': 5, 'FX': 5},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [6]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_transpose_ConvTranspose_14_PART_0_21_fuse_bias_add_output@@ConvTranspose_14_22'},
    8: {   'operator_type': 'Conv_from_deconv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 1, 'C': 56, 'OY': 256, 'OX': 256, 'FY': 5, 'FX': 4},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [6]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_transpose_ConvTranspose_14_PART_0_21_fuse_bias_add_output@@ConvTranspose_14_22'},
    9: {   'operator_type': 'Conv_from_deconv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 1, 'C': 56, 'OY': 256, 'OX': 256, 'FY': 4, 'FX': 5},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [6]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_transpose_ConvTranspose_14_PART_0_21_fuse_bias_add_output@@ConvTranspose_14_22'},
    10: {   'operator_type': 'Conv_from_deconv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1, 'C': 56, 'OY': 256, 'OX': 256, 'FY': 4, 'FX': 4},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [6]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_transpose_ConvTranspose_14_PART_0_21_fuse_bias_add_output@@ConvTranspose_14_22'},
    11: {   'operator_type': 'Contract',
            'equation': 'contract',
            'loop_dim_size': {'B': 1, 'G': 1, 'OY': 512, 'OX': 512},
            'operand_precision': {'O': 8, 'O_final': 8, 'I': 8},
            'operand_source': {'X0': [10], 'X1': [9], 'X2': [8], 'X3': [7]},
            'constant_operands': [],
            'core_allocation': 1,
            'memory_operand_links': {'O': 'O', 'I': 'I1'},
            'name': 'conv2d_transpose_ConvTranspose_14_PART_0_21_fuse_bias_add_output@@ConvTranspose_14_22'}}
