workload ={   -1: {   'equation': 'input',
            'loop_dim_size': {'B': 1, 'G': 3, 'OY': 224, 'OX': 224},
            'precision': 8,
            'core_allocation': 1,
            'memory_operand_links': {'O': 'I1'}},
    0: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 32, 'C': 3, 'OY': 112, 'OX': 112, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [-1]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv1_0_fuse_multiply_1_fuse_add_conv1/bn_PART_0_2'},
    1: {   'operator_type': 'dw_Conv',
           'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'G': 32, 'OY': 112, 'OX': 112, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [0]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv2_1/dw_4_fuse_multiply_5_fuse_add_conv2_1/dw/bn_PART_0_6'},
    2: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 64, 'C': 32, 'OY': 112, 'OX': 112, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [1]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv2_1/sep_8_fuse_multiply_9_fuse_add_conv2_1/sep/bn_PART_0_10'},
    3: {   'operator_type': 'dw_Conv',
           'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
           'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'G': 64, 'OY': 56, 'OX': 56, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [2]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv2_2/dw_12_fuse_multiply_13_fuse_add_conv2_2/dw/bn_PART_0_14'},
    4: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 128, 'C': 64, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [3]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv2_2/sep_16_fuse_multiply_17_fuse_add_conv2_2/sep/bn_PART_0_18'},
    5: {   'operator_type': 'dw_Conv',
           'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'G': 128, 'OY': 56, 'OX': 56, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [4]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv3_1/dw_20_fuse_multiply_21_fuse_add_conv3_1/dw/bn_PART_0_22'},
    6: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 128, 'C': 128, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [5]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv3_1/sep_24_fuse_multiply_25_fuse_add_conv3_1/sep/bn_PART_0_26'},
    7: {   'operator_type': 'dw_Conv',
           'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
           'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'G': 128, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [6]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv3_2/dw_28_fuse_multiply_29_fuse_add_conv3_2/dw/bn_PART_0_30'},
    8: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 256, 'C': 128, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [7]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv3_2/sep_32_fuse_multiply_33_fuse_add_conv3_2/sep/bn_PART_0_34'},
    9: {   'operator_type': 'dw_Conv',
           'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'G': 256, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [8]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv4_1/dw_36_fuse_multiply_37_fuse_add_conv4_1/dw/bn_PART_0_38'},
    10: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 256, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [9]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_1/sep_40_fuse_multiply_41_fuse_add_conv4_1/sep/bn_PART_0_42'},
    11: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 256, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [10]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_2/dw_44_fuse_multiply_45_fuse_add_conv4_2/dw/bn_PART_0_46'},
    12: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [11]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_2/sep_48_fuse_multiply_49_fuse_add_conv4_2/sep/bn_PART_0_50'},
    13: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 512, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [12]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_1/dw_52_fuse_multiply_53_fuse_add_conv5_1/dw/bn_PART_0_54'},
    14: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 512, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [13]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_1/sep_56_fuse_multiply_57_fuse_add_conv5_1/sep/bn_PART_0_58'},
    15: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 512, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [14]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_2/dw_60_fuse_multiply_61_fuse_add_conv5_2/dw/bn_PART_0_62'},
    16: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 512, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [15]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_2/sep_64_fuse_multiply_65_fuse_add_conv5_2/sep/bn_PART_0_66'},
    17: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 512, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [16]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_3/dw_68_fuse_multiply_69_fuse_add_conv5_3/dw/bn_PART_0_70'},
    18: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 512, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [17]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_3/sep_72_fuse_multiply_73_fuse_add_conv5_3/sep/bn_PART_0_74'},
    19: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 512, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [18]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_4/dw_76_fuse_multiply_77_fuse_add_conv5_4/dw/bn_PART_0_78'},
    20: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 512, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [19]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_4/sep_80_fuse_multiply_81_fuse_add_conv5_4/sep/bn_PART_0_82'},
    21: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 512, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [20]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_5/dw_84_fuse_multiply_85_fuse_add_conv5_5/dw/bn_PART_0_86'},
    22: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 512, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [21]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_5/sep_88_fuse_multiply_89_fuse_add_conv5_5/sep/bn_PART_0_90'},
    23: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 512, 'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [22]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_6/dw_92_fuse_multiply_93_fuse_add_conv5_6/dw/bn_PART_0_94'},
    24: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1024, 'C': 512, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [23]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_6/sep_96_fuse_multiply_97_fuse_add_conv5_6/sep/bn_PART_0_98'},
    25: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 1024, 'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [24]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv6/dw_100_fuse_multiply_101_fuse_add_conv6/dw/bn_PART_0_102'},
    26: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1024, 'C': 1024, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [25]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv6/sep_104_fuse_multiply_105_fuse_add_conv6/sep/bn_PART_0_106'},
    27: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 1024, 'OY': 1, 'OX': 1, 'FY': 7, 'FX': 7},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [26]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'global_avg_pool2d_pool6_108'},
    28: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1000, 'C': 1024, 'OY': 1, 'OX': 1, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [27]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_fc7_PART_0_109_fuse_bias_add_fc7_110'}}
