workload ={   -1: {   'equation': 'input',
            'loop_dim_size': {'B': 1, 'G': 3, 'OY': 224, 'OX': 224},
            'precision': 8,
            'core_allocation': 1,
            'memory_operand_links': {'O': 'I1'}},
    0: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 64, 'C': 3, 'OY': 112, 'OX': 112, 'FY': 7, 'FX': 7},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [-1]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_conv1/7x7_s2_1_PART_0_0_fuse_bias_add_Conv_conv1/7x7_s2_1_1'},
    1: {   'operator_type': 'Pool',
           'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
           'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'G': 64, 'OY': 55, 'OX': 55, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
           'operand_source': {'W': [], 'I': [0]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 32)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'max_pool2d_MaxPool_pool1/3x3_s2_1_3'},
    2: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 64, 'C': 64, 'OY': 55, 'OX': 55, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [1]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_conv2/3x3_reduce_1_PART_0_5_fuse_bias_add_Conv_conv2/3x3_reduce_1_6'},
    3: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 192, 'C': 64, 'OY': 55, 'OX': 55, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [2]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_conv2/3x3_1_PART_0_8_fuse_bias_add_Conv_conv2/3x3_1_9'},
    4: {   'operator_type': 'Pool',
           'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
           'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'G': 192, 'OY': 27, 'OX': 27, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
           'operand_source': {'W': [], 'I': [3]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 32)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'max_pool2d_MaxPool_pool2/3x3_s2_1_12'},
    5: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 64, 'C': 192, 'OY': 27, 'OX': 27, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [4]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_inception_3a/1x1_1_PART_0_13_fuse_bias_add_Conv_inception_3a/1x1_1_14'},
    6: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 96, 'C': 192, 'OY': 27, 'OX': 27, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [4]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_inception_3a/3x3_reduce_1_PART_0_16_fuse_bias_add_Conv_inception_3a/3x3_reduce_1_17'},
    7: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 128, 'C': 96, 'OY': 27, 'OX': 27, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [6]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_inception_3a/3x3_1_PART_0_19_fuse_bias_add_Conv_inception_3a/3x3_1_20'},
    8: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 16, 'C': 192, 'OY': 27, 'OX': 27, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [4]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_inception_3a/5x5_reduce_1_PART_0_22_fuse_bias_add_Conv_inception_3a/5x5_reduce_1_23'},
    9: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 32, 'C': 16, 'OY': 27, 'OX': 27, 'FY': 5, 'FX': 5},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [8]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_Conv_inception_3a/5x5_1_PART_0_25_fuse_bias_add_Conv_inception_3a/5x5_1_26'},
    10: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 192, 'OY': 27, 'OX': 27, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [4]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'max_pool2d_MaxPool_inception_3a/pool_1_28'},
    11: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 32, 'C': 192, 'OY': 27, 'OX': 27, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [10]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_3a/pool_proj_1_PART_0_29_fuse_bias_add_Conv_inception_3a/pool_proj_1_30'},
    12: {   'operator_type': 'Concat',
            'equation': 'concat',
            'loop_dim_size': {'B': 1, 'G': 256, 'OY': 27, 'OX': 27},
            'operand_precision': {'O': 8, 'O_final': 8, 'I': 8},
            'operand_source': {'X0': [5], 'X1': [7], 'X2': [9], 'X3': [11]},
            'constant_operands': [],
            'core_allocation': 1,
            'memory_operand_links': {'O': 'O', 'I': 'I1'},
            'name': 'concatenate_Concat_inception_3a/output_1_32'},
    13: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 256, 'OY': 27, 'OX': 27, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [12]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_3b/1x1_1_PART_0_33_fuse_bias_add_Conv_inception_3b/1x1_1_34'},
    14: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 256, 'OY': 27, 'OX': 27, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [12]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_3b/3x3_reduce_1_PART_0_36_fuse_bias_add_Conv_inception_3b/3x3_reduce_1_37'},
    15: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 192, 'C': 128, 'OY': 27, 'OX': 27, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [14]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_3b/3x3_1_PART_0_39_fuse_bias_add_Conv_inception_3b/3x3_1_40'},
    16: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 32, 'C': 256, 'OY': 27, 'OX': 27, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [12]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_3b/5x5_reduce_1_PART_0_42_fuse_bias_add_Conv_inception_3b/5x5_reduce_1_43'},
    17: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 96, 'C': 32, 'OY': 27, 'OX': 27, 'FY': 5, 'FX': 5},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [16]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_3b/5x5_1_PART_0_45_fuse_bias_add_Conv_inception_3b/5x5_1_46'},
    18: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 256, 'OY': 27, 'OX': 27, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [12]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'max_pool2d_MaxPool_inception_3b/pool_1_48'},
    19: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 256, 'OY': 27, 'OX': 27, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [18]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_3b/pool_proj_1_PART_0_49_fuse_bias_add_Conv_inception_3b/pool_proj_1_50'},
    20: {   'operator_type': 'Concat',
            'equation': 'concat',
            'loop_dim_size': {'B': 1, 'G': 480, 'OY': 27, 'OX': 27},
            'operand_precision': {'O': 8, 'O_final': 8, 'I': 8},
            'operand_source': {'X0': [13], 'X1': [15], 'X2': [17], 'X3': [19]},
            'constant_operands': [],
            'core_allocation': 1,
            'memory_operand_links': {'O': 'O', 'I': 'I1'},
            'name': 'concatenate_Concat_inception_3b/output_1_52'},
    21: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 480, 'OY': 13, 'OX': 13, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [20]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'max_pool2d_MaxPool_pool3/3x3_s2_1_53'},
    22: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 192, 'C': 480, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [21]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4a/1x1_1_PART_0_54_fuse_bias_add_Conv_inception_4a/1x1_1_55'},
    23: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 96, 'C': 480, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [21]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4a/3x3_reduce_1_PART_0_57_fuse_bias_add_Conv_inception_4a/3x3_reduce_1_58'},
    24: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 208, 'C': 96, 'OY': 13, 'OX': 13, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [23]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4a/3x3_1_PART_0_60_fuse_bias_add_Conv_inception_4a/3x3_1_61'},
    25: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 16, 'C': 480, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [21]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4a/5x5_reduce_1_PART_0_63_fuse_bias_add_Conv_inception_4a/5x5_reduce_1_64'},
    26: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 48, 'C': 16, 'OY': 13, 'OX': 13, 'FY': 5, 'FX': 5},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [25]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4a/5x5_1_PART_0_66_fuse_bias_add_Conv_inception_4a/5x5_1_67'},
    27: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 480, 'OY': 13, 'OX': 13, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [21]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'max_pool2d_MaxPool_inception_4a/pool_1_69'},
    28: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 480, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [27]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4a/pool_proj_1_PART_0_70_fuse_bias_add_Conv_inception_4a/pool_proj_1_71'},
    29: {   'operator_type': 'Concat',
            'equation': 'concat',
            'loop_dim_size': {'B': 1, 'G': 512, 'OY': 13, 'OX': 13},
            'operand_precision': {'O': 8, 'O_final': 8, 'I': 8},
            'operand_source': {'X0': [22], 'X1': [24], 'X2': [26], 'X3': [28]},
            'constant_operands': [],
            'core_allocation': 1,
            'memory_operand_links': {'O': 'O', 'I': 'I1'},
            'name': 'concatenate_Concat_inception_4a/output_1_73'},
    30: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 160, 'C': 512, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [29]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4b/1x1_1_PART_0_74_fuse_bias_add_Conv_inception_4b/1x1_1_75'},
    31: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 112, 'C': 512, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [29]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4b/3x3_reduce_1_PART_0_77_fuse_bias_add_Conv_inception_4b/3x3_reduce_1_78'},
    32: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 224, 'C': 112, 'OY': 13, 'OX': 13, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [31]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4b/3x3_1_PART_0_80_fuse_bias_add_Conv_inception_4b/3x3_1_81'},
    33: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 24, 'C': 512, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [29]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4b/5x5_reduce_1_PART_0_83_fuse_bias_add_Conv_inception_4b/5x5_reduce_1_84'},
    34: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 24, 'OY': 13, 'OX': 13, 'FY': 5, 'FX': 5},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [33]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4b/5x5_1_PART_0_86_fuse_bias_add_Conv_inception_4b/5x5_1_87'},
    35: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 512, 'OY': 13, 'OX': 13, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [29]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'max_pool2d_MaxPool_inception_4b/pool_1_89'},
    36: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 512, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [35]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4b/pool_proj_1_PART_0_90_fuse_bias_add_Conv_inception_4b/pool_proj_1_91'},
    37: {   'operator_type': 'Concat',
            'equation': 'concat',
            'loop_dim_size': {'B': 1, 'G': 512, 'OY': 13, 'OX': 13},
            'operand_precision': {'O': 8, 'O_final': 8, 'I': 8},
            'operand_source': {'X0': [30], 'X1': [32], 'X2': [34], 'X3': [36]},
            'constant_operands': [],
            'core_allocation': 1,
            'memory_operand_links': {'O': 'O', 'I': 'I1'},
            'name': 'concatenate_Concat_inception_4b/output_1_93'},
    38: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 512, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [37]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4c/1x1_1_PART_0_94_fuse_bias_add_Conv_inception_4c/1x1_1_95'},
    39: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 512, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [37]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4c/3x3_reduce_1_PART_0_97_fuse_bias_add_Conv_inception_4c/3x3_reduce_1_98'},
    40: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 128, 'OY': 13, 'OX': 13, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [39]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4c/3x3_1_PART_0_100_fuse_bias_add_Conv_inception_4c/3x3_1_101'},
    41: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 24, 'C': 512, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [37]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4c/5x5_reduce_1_PART_0_103_fuse_bias_add_Conv_inception_4c/5x5_reduce_1_104'},
    42: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 24, 'OY': 13, 'OX': 13, 'FY': 5, 'FX': 5},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [41]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4c/5x5_1_PART_0_106_fuse_bias_add_Conv_inception_4c/5x5_1_107'},
    43: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 512, 'OY': 13, 'OX': 13, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [37]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'max_pool2d_MaxPool_inception_4c/pool_1_109'},
    44: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 512, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [43]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4c/pool_proj_1_PART_0_110_fuse_bias_add_Conv_inception_4c/pool_proj_1_111'},
    45: {   'operator_type': 'Concat',
            'equation': 'concat',
            'loop_dim_size': {'B': 1, 'G': 512, 'OY': 13, 'OX': 13},
            'operand_precision': {'O': 8, 'O_final': 8, 'I': 8},
            'operand_source': {'X0': [38], 'X1': [40], 'X2': [42], 'X3': [44]},
            'constant_operands': [],
            'core_allocation': 1,
            'memory_operand_links': {'O': 'O', 'I': 'I1'},
            'name': 'concatenate_Concat_inception_4c/output_1_113'},
    46: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 112, 'C': 512, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [45]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4d/1x1_1_PART_0_114_fuse_bias_add_Conv_inception_4d/1x1_1_115'},
    47: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 144, 'C': 512, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [45]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4d/3x3_reduce_1_PART_0_117_fuse_bias_add_Conv_inception_4d/3x3_reduce_1_118'},
    48: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 288, 'C': 144, 'OY': 13, 'OX': 13, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [47]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4d/3x3_1_PART_0_120_fuse_bias_add_Conv_inception_4d/3x3_1_121'},
    49: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 32, 'C': 512, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [45]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4d/5x5_reduce_1_PART_0_123_fuse_bias_add_Conv_inception_4d/5x5_reduce_1_124'},
    50: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 32, 'OY': 13, 'OX': 13, 'FY': 5, 'FX': 5},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [49]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4d/5x5_1_PART_0_126_fuse_bias_add_Conv_inception_4d/5x5_1_127'},
    51: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 512, 'OY': 13, 'OX': 13, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [45]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'max_pool2d_MaxPool_inception_4d/pool_1_129'},
    52: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 512, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [51]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4d/pool_proj_1_PART_0_130_fuse_bias_add_Conv_inception_4d/pool_proj_1_131'},
    53: {   'operator_type': 'Concat',
            'equation': 'concat',
            'loop_dim_size': {'B': 1, 'G': 528, 'OY': 13, 'OX': 13},
            'operand_precision': {'O': 8, 'O_final': 8, 'I': 8},
            'operand_source': {'X0': [46], 'X1': [48], 'X2': [50], 'X3': [52]},
            'constant_operands': [],
            'core_allocation': 1,
            'memory_operand_links': {'O': 'O', 'I': 'I1'},
            'name': 'concatenate_Concat_inception_4d/output_1_133'},
    54: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 528, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [53]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4e/1x1_1_PART_0_134_fuse_bias_add_Conv_inception_4e/1x1_1_135'},
    55: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 160, 'C': 528, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [53]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4e/3x3_reduce_1_PART_0_137_fuse_bias_add_Conv_inception_4e/3x3_reduce_1_138'},
    56: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 320, 'C': 160, 'OY': 13, 'OX': 13, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [55]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4e/3x3_1_PART_0_140_fuse_bias_add_Conv_inception_4e/3x3_1_141'},
    57: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 32, 'C': 528, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [53]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4e/5x5_reduce_1_PART_0_143_fuse_bias_add_Conv_inception_4e/5x5_reduce_1_144'},
    58: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 32, 'OY': 13, 'OX': 13, 'FY': 5, 'FX': 5},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [57]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4e/5x5_1_PART_0_146_fuse_bias_add_Conv_inception_4e/5x5_1_147'},
    59: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 528, 'OY': 13, 'OX': 13, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [53]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'max_pool2d_MaxPool_inception_4e/pool_1_149'},
    60: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 528, 'OY': 13, 'OX': 13, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [59]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_4e/pool_proj_1_PART_0_150_fuse_bias_add_Conv_inception_4e/pool_proj_1_151'},
    61: {   'operator_type': 'Concat',
            'equation': 'concat',
            'loop_dim_size': {'B': 1, 'G': 832, 'OY': 13, 'OX': 13},
            'operand_precision': {'O': 8, 'O_final': 8, 'I': 8},
            'operand_source': {'X0': [54], 'X1': [56], 'X2': [58], 'X3': [60]},
            'constant_operands': [],
            'core_allocation': 1,
            'memory_operand_links': {'O': 'O', 'I': 'I1'},
            'name': 'concatenate_Concat_inception_4e/output_1_153'},
    62: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 832, 'OY': 6, 'OX': 6, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [61]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'max_pool2d_MaxPool_pool4/3x3_s2_1_154'},
    63: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 832, 'OY': 6, 'OX': 6, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [62]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_5a/1x1_1_PART_0_155_fuse_bias_add_Conv_inception_5a/1x1_1_156'},
    64: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 160, 'C': 832, 'OY': 6, 'OX': 6, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [62]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_5a/3x3_reduce_1_PART_0_158_fuse_bias_add_Conv_inception_5a/3x3_reduce_1_159'},
    65: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 320, 'C': 160, 'OY': 6, 'OX': 6, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [64]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_5a/3x3_1_PART_0_161_fuse_bias_add_Conv_inception_5a/3x3_1_162'},
    66: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 32, 'C': 832, 'OY': 6, 'OX': 6, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [62]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_5a/5x5_reduce_1_PART_0_164_fuse_bias_add_Conv_inception_5a/5x5_reduce_1_165'},
    67: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 32, 'OY': 6, 'OX': 6, 'FY': 5, 'FX': 5},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [66]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_5a/5x5_1_PART_0_167_fuse_bias_add_Conv_inception_5a/5x5_1_168'},
    68: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 832, 'OY': 6, 'OX': 6, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [62]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'max_pool2d_MaxPool_inception_5a/pool_1_170'},
    69: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 832, 'OY': 6, 'OX': 6, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [68]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_5a/pool_proj_1_PART_0_171_fuse_bias_add_Conv_inception_5a/pool_proj_1_172'},
    70: {   'operator_type': 'Concat',
            'equation': 'concat',
            'loop_dim_size': {'B': 1, 'G': 832, 'OY': 6, 'OX': 6},
            'operand_precision': {'O': 8, 'O_final': 8, 'I': 8},
            'operand_source': {'X0': [63], 'X1': [65], 'X2': [67], 'X3': [69]},
            'constant_operands': [],
            'core_allocation': 1,
            'memory_operand_links': {'O': 'O', 'I': 'I1'},
            'name': 'concatenate_Concat_inception_5a/output_1_174'},
    71: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 384, 'C': 832, 'OY': 6, 'OX': 6, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [70]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_5b/1x1_1_PART_0_175_fuse_bias_add_Conv_inception_5b/1x1_1_176'},
    72: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 192, 'C': 832, 'OY': 6, 'OX': 6, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [70]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_5b/3x3_reduce_1_PART_0_178_fuse_bias_add_Conv_inception_5b/3x3_reduce_1_179'},
    73: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 384, 'C': 192, 'OY': 6, 'OX': 6, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [72]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_5b/3x3_1_PART_0_181_fuse_bias_add_Conv_inception_5b/3x3_1_182'},
    74: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 48, 'C': 832, 'OY': 6, 'OX': 6, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [70]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_5b/5x5_reduce_1_PART_0_184_fuse_bias_add_Conv_inception_5b/5x5_reduce_1_185'},
    75: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 48, 'OY': 6, 'OX': 6, 'FY': 5, 'FX': 5},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [74]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_5b/5x5_1_PART_0_187_fuse_bias_add_Conv_inception_5b/5x5_1_188'},
    76: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 832, 'OY': 6, 'OX': 6, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [70]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'max_pool2d_MaxPool_inception_5b/pool_1_190'},
    77: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 832, 'OY': 6, 'OX': 6, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [76]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_Conv_inception_5b/pool_proj_1_PART_0_191_fuse_bias_add_Conv_inception_5b/pool_proj_1_192'},
    78: {   'operator_type': 'Concat',
            'equation': 'concat',
            'loop_dim_size': {'B': 1, 'G': 1024, 'OY': 6, 'OX': 6},
            'operand_precision': {'O': 8, 'O_final': 8, 'I': 8},
            'operand_source': {'X0': [71], 'X1': [73], 'X2': [75], 'X3': [77]},
            'constant_operands': [],
            'core_allocation': 1,
            'memory_operand_links': {'O': 'O', 'I': 'I1'},
            'name': 'concatenate_Concat_inception_5b/output_1_194'},
    79: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 1024, 'OY': 1, 'OX': 1, 'FY': 7, 'FX': 7},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [78]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'avg_pool2d_AveragePool_pool5/7x7_s1_1_195'},
    80: {   'operator_type': 'Dense',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1000, 'C': 1024, 'OY': 1, 'OX': 1, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [79]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('B', 4), 'D4': ('B', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'dense_Gemm_loss3/classifier_1_PART_0_197_fuse_add_Gemm_loss3/classifier_1_198'}}
