workload ={   -1: {   'equation': 'input',
            'loop_dim_size': {'B': 1, 'G': 3, 'OY': 224, 'OX': 224},
            'precision': 8,
            'core_allocation': 1,
            'memory_operand_links': {'O': 'I1'}},
    0: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 32, 'C': 3, 'OY': 112, 'OX': 112, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [-1]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv1_0_fuse_multiply_1_fuse_add_conv1/bn_PART_0_2'},
    1: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 32, 'C': 32, 'OY': 112, 'OX': 112, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [0]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv2_1/expand_4_fuse_multiply_5_fuse_add_conv2_1/expand/bn_PART_0_6'},
    2: {   'operator_type': 'dw_Conv',
           'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'G': 32, 'OY': 112, 'OX': 112, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [1]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv2_1/dwise_8_fuse_multiply_9_fuse_add_conv2_1/dwise/bn_PART_0_10'},
    3: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 16, 'C': 32, 'OY': 112, 'OX': 112, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [2]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv2_1/linear_12_fuse_multiply_13_fuse_add_conv2_1/linear/bn_PART_0_14'},
    4: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 96, 'C': 16, 'OY': 112, 'OX': 112, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [3]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv2_2/expand_15_fuse_multiply_16_fuse_add_conv2_2/expand/bn_PART_0_17'},
    5: {   'operator_type': 'dw_Conv',
           'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
           'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'G': 96, 'OY': 56, 'OX': 56, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [4]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv2_2/dwise_19_fuse_multiply_20_fuse_add_conv2_2/dwise/bn_PART_0_21'},
    6: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 24, 'C': 96, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [5]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv2_2/linear_23_fuse_multiply_24_fuse_add_conv2_2/linear/bn_PART_0_25'},
    7: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 144, 'C': 24, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [6]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv3_1/expand_26_fuse_multiply_27_fuse_add_conv3_1/expand/bn_PART_0_28'},
    8: {   'operator_type': 'dw_Conv',
           'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'G': 144, 'OY': 56, 'OX': 56, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [7]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv3_1/dwise_30_fuse_multiply_31_fuse_add_conv3_1/dwise/bn_PART_0_32'},
    9: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 24, 'C': 144, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [8]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv3_1/linear_34_fuse_multiply_35_fuse_add_conv3_1/linear/bn_PART_0_36'},
    10: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 24, 'D': 1, 'OY': 56, 'OX': 56},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [6], 'Y': [9]},
            'constant_operands': [],
            'operand_precision': {'O': 16, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'name': 'add_block_3_1_37'},
    11: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 144, 'C': 24, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [10]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv3_2/expand_38_fuse_multiply_39_fuse_add_conv3_2/expand/bn_PART_0_40'},
    12: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 144, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [11]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv3_2/dwise_42_fuse_multiply_43_fuse_add_conv3_2/dwise/bn_PART_0_44'},
    13: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 32, 'C': 144, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [12]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv3_2/linear_46_fuse_multiply_47_fuse_add_conv3_2/linear/bn_PART_0_48'},
    14: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 192, 'C': 32, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [13]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_1/expand_49_fuse_multiply_50_fuse_add_conv4_1/expand/bn_PART_0_51'},
    15: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 192, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [14]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_1/dwise_53_fuse_multiply_54_fuse_add_conv4_1/dwise/bn_PART_0_55'},
    16: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 32, 'C': 192, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [15]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_1/linear_57_fuse_multiply_58_fuse_add_conv4_1/linear/bn_PART_0_59'},
    17: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 32, 'D': 1, 'OY': 28, 'OX': 28},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [13], 'Y': [16]},
            'constant_operands': [],
            'operand_precision': {'O': 16, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'name': 'add_block_4_1_60'},
    18: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 192, 'C': 32, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [17]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_2/expand_61_fuse_multiply_62_fuse_add_conv4_2/expand/bn_PART_0_63'},
    19: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 192, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [18]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_2/dwise_65_fuse_multiply_66_fuse_add_conv4_2/dwise/bn_PART_0_67'},
    20: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 32, 'C': 192, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [19]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_2/linear_69_fuse_multiply_70_fuse_add_conv4_2/linear/bn_PART_0_71'},
    21: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 32, 'D': 1, 'OY': 28, 'OX': 28},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [17], 'Y': [20]},
            'constant_operands': [],
            'operand_precision': {'O': 16, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'name': 'add_block_4_2_72'},
    22: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 192, 'C': 32, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [21]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_3/expand_73_fuse_multiply_74_fuse_add_conv4_3/expand/bn_PART_0_75'},
    23: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 192, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [22]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_3/dwise_77_fuse_multiply_78_fuse_add_conv4_3/dwise/bn_PART_0_79'},
    24: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 192, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [23]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_3/linear_81_fuse_multiply_82_fuse_add_conv4_3/linear/bn_PART_0_83'},
    25: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 384, 'C': 64, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [24]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_4/expand_84_fuse_multiply_85_fuse_add_conv4_4/expand/bn_PART_0_86'},
    26: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 384, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [25]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_4/dwise_88_fuse_multiply_89_fuse_add_conv4_4/dwise/bn_PART_0_90'},
    27: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 384, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [26]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_4/linear_92_fuse_multiply_93_fuse_add_conv4_4/linear/bn_PART_0_94'},
    28: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 64, 'D': 1, 'OY': 28, 'OX': 28},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [24], 'Y': [27]},
            'constant_operands': [],
            'operand_precision': {'O': 16, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'name': 'add_block_4_4_95'},
    29: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 384, 'C': 64, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [28]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_5/expand_96_fuse_multiply_97_fuse_add_conv4_5/expand/bn_PART_0_98'},
    30: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 384, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [29]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_5/dwise_100_fuse_multiply_101_fuse_add_conv4_5/dwise/bn_PART_0_102'},
    31: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 384, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [30]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_5/linear_104_fuse_multiply_105_fuse_add_conv4_5/linear/bn_PART_0_106'},
    32: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 64, 'D': 1, 'OY': 28, 'OX': 28},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [28], 'Y': [31]},
            'constant_operands': [],
            'operand_precision': {'O': 16, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'name': 'add_block_4_5_107'},
    33: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 384, 'C': 64, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [32]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_6/expand_108_fuse_multiply_109_fuse_add_conv4_6/expand/bn_PART_0_110'},
    34: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 384, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [33]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_6/dwise_112_fuse_multiply_113_fuse_add_conv4_6/dwise/bn_PART_0_114'},
    35: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 384, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [34]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_6/linear_116_fuse_multiply_117_fuse_add_conv4_6/linear/bn_PART_0_118'},
    36: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 64, 'D': 1, 'OY': 28, 'OX': 28},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [32], 'Y': [35]},
            'constant_operands': [],
            'operand_precision': {'O': 16, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'name': 'add_block_4_6_119'},
    37: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 384, 'C': 64, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [36]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_7/expand_120_fuse_multiply_121_fuse_add_conv4_7/expand/bn_PART_0_122'},
    38: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 384, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [37]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_7/dwise_124_fuse_multiply_125_fuse_add_conv4_7/dwise/bn_PART_0_126'},
    39: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 96, 'C': 384, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [38]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv4_7/linear_128_fuse_multiply_129_fuse_add_conv4_7/linear/bn_PART_0_130'},
    40: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 576, 'C': 96, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [39]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_1/expand_131_fuse_multiply_132_fuse_add_conv5_1/expand/bn_PART_0_133'},
    41: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 576, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [40]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_1/dwise_135_fuse_multiply_136_fuse_add_conv5_1/dwise/bn_PART_0_137'},
    42: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 96, 'C': 576, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [41]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_1/linear_139_fuse_multiply_140_fuse_add_conv5_1/linear/bn_PART_0_141'},
    43: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 96, 'D': 1, 'OY': 14, 'OX': 14},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [39], 'Y': [42]},
            'constant_operands': [],
            'operand_precision': {'O': 16, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'name': 'add_block_5_1_142'},
    44: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 576, 'C': 96, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [43]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_2/expand_143_fuse_multiply_144_fuse_add_conv5_2/expand/bn_PART_0_145'},
    45: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 576, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [44]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_2/dwise_147_fuse_multiply_148_fuse_add_conv5_2/dwise/bn_PART_0_149'},
    46: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 96, 'C': 576, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [45]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_2/linear_151_fuse_multiply_152_fuse_add_conv5_2/linear/bn_PART_0_153'},
    47: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 96, 'D': 1, 'OY': 14, 'OX': 14},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [43], 'Y': [46]},
            'constant_operands': [],
            'operand_precision': {'O': 16, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'name': 'add_block_5_2_154'},
    48: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 576, 'C': 96, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [47]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_3/expand_155_fuse_multiply_156_fuse_add_conv5_3/expand/bn_PART_0_157'},
    49: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 576, 'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [48]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_3/dwise_159_fuse_multiply_160_fuse_add_conv5_3/dwise/bn_PART_0_161'},
    50: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 160, 'C': 576, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [49]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv5_3/linear_163_fuse_multiply_164_fuse_add_conv5_3/linear/bn_PART_0_165'},
    51: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 960, 'C': 160, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [50]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv6_1/expand_166_fuse_multiply_167_fuse_add_conv6_1/expand/bn_PART_0_168'},
    52: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 960, 'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [51]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv6_1/dwise_170_fuse_multiply_171_fuse_add_conv6_1/dwise/bn_PART_0_172'},
    53: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 160, 'C': 960, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [52]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv6_1/linear_174_fuse_multiply_175_fuse_add_conv6_1/linear/bn_PART_0_176'},
    54: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 160, 'D': 1, 'OY': 7, 'OX': 7},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [50], 'Y': [53]},
            'constant_operands': [],
            'operand_precision': {'O': 16, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'name': 'add_block_6_1_177'},
    55: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 960, 'C': 160, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [54]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv6_2/expand_178_fuse_multiply_179_fuse_add_conv6_2/expand/bn_PART_0_180'},
    56: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 960, 'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [55]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv6_2/dwise_182_fuse_multiply_183_fuse_add_conv6_2/dwise/bn_PART_0_184'},
    57: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 160, 'C': 960, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [56]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv6_2/linear_186_fuse_multiply_187_fuse_add_conv6_2/linear/bn_PART_0_188'},
    58: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 160, 'D': 1, 'OY': 7, 'OX': 7},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [54], 'Y': [57]},
            'constant_operands': [],
            'operand_precision': {'O': 16, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'name': 'add_block_6_2_189'},
    59: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 960, 'C': 160, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [58]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv6_3/expand_190_fuse_multiply_191_fuse_add_conv6_3/expand/bn_PART_0_192'},
    60: {   'operator_type': 'dw_Conv',
            'equation': 'O[b][g][oy][ox]+=W[g][fy][fx]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 960, 'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [59]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv6_3/dwise_194_fuse_multiply_195_fuse_add_conv6_3/dwise/bn_PART_0_196'},
    61: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 320, 'C': 960, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [60]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv6_3/linear_198_fuse_multiply_199_fuse_add_conv6_3/linear/bn_PART_0_200'},
    62: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1280, 'C': 320, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [61]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_conv6_4_201_fuse_multiply_202_fuse_add_conv6_4/bn_PART_0_203'},
    63: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 1280, 'OY': 1, 'OX': 1, 'FY': 7, 'FX': 7},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [62]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 32)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'global_avg_pool2d_pool6_205'},
    64: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1000, 'C': 1280, 'OY': 1, 'OX': 1, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [63]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 32), 'D2': ('C', 2), 'D3': ('OX', 4), 'D4': ('OY', 4)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_fc7_PART_0_206_fuse_bias_add_fc7_207'}}
