workload ={   -1: {   'equation': 'input',
            'loop_dim_size': {'B': 1, 'G': 3, 'OY': 224, 'OX': 224},
            'precision': 8,
            'core_allocation': 1,
            'memory_operand_links': {'O': 'I1'}},
    0: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 64, 'C': 3, 'OY': 112, 'OX': 112, 'FY': 7, 'FX': 7},
           'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [-1]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_conv1_PART_0_0_fuse_bias_add_conv1_1_fuse_multiply_2_fuse_add_bn_conv1_PART_0_3'},
    1: {   'operator_type': 'Pool',
           'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
           'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'G': 64, 'OY': 56, 'OX': 56, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 32, 'O_final': 8, 'W': 0, 'I': 8},
           'operand_source': {'W': [], 'I': [0]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 8)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'max_pool2d_pool1_5'},
    2: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 256, 'C': 64, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [1]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_res2a_branch1_6_fuse_multiply_7_fuse_add_bn2a_branch1_PART_0_8'},
    3: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 64, 'C': 64, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [1]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_res2a_branch2a_9_fuse_multiply_10_fuse_add_bn2a_branch2a_PART_0_11'},
    4: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 64, 'C': 64, 'OY': 56, 'OX': 56, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [3]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_res2a_branch2b_13_fuse_multiply_14_fuse_add_bn2a_branch2b_PART_0_15'},
    5: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 256, 'C': 64, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [4]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_res2a_branch2c_17_fuse_multiply_18_fuse_add_bn2a_branch2c_PART_0_19'},
    6: {   'operator_type': 'Add',
           'equation_relations': [],
           'loop_dim_size': {'B': 1, 'G': 256, 'D': 1, 'OY': 56, 'OX': 56},
           'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
           'operand_source': {'X': [2], 'Y': [5]},
           'constant_operands': [],
           'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
           'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('G', 8)},
           'name': 'add_res2a_20'},
    7: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 64, 'C': 256, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [6]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_res2b_branch2a_22_fuse_multiply_23_fuse_add_bn2b_branch2a_PART_0_24'},
    8: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 64, 'C': 64, 'OY': 56, 'OX': 56, 'FY': 3, 'FX': 3},
           'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [7]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_res2b_branch2b_26_fuse_multiply_27_fuse_add_bn2b_branch2b_PART_0_28'},
    9: {   'operator_type': 'Conv',
           'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
           'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
           'loop_dim_size': {'B': 1, 'K': 256, 'C': 64, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
           'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
           'operand_source': {'W': [], 'I': [8]},
           'constant_operands': ['W'],
           'core_allocation': 1,
           'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
           'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
           'name': 'conv2d_res2b_branch2c_30_fuse_multiply_31_fuse_add_bn2b_branch2c_PART_0_32'},
    10: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 256, 'D': 1, 'OY': 56, 'OX': 56},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [6], 'Y': [9]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res2b_33'},
    11: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 256, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [10]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res2c_branch2a_35_fuse_multiply_36_fuse_add_bn2c_branch2a_PART_0_37'},
    12: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 64, 'C': 64, 'OY': 56, 'OX': 56, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [11]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res2c_branch2b_39_fuse_multiply_40_fuse_add_bn2c_branch2b_PART_0_41'},
    13: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 64, 'OY': 56, 'OX': 56, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [12]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res2c_branch2c_43_fuse_multiply_44_fuse_add_bn2c_branch2c_PART_0_45'},
    14: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 256, 'D': 1, 'OY': 56, 'OX': 56},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [10], 'Y': [13]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res2c_46'},
    15: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 256, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [14]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3a_branch1_48_fuse_multiply_49_fuse_add_bn3a_branch1_PART_0_50'},
    16: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 256, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [14]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3a_branch2a_51_fuse_multiply_52_fuse_add_bn3a_branch2a_PART_0_53'},
    17: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 128, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [16]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3a_branch2b_55_fuse_multiply_56_fuse_add_bn3a_branch2b_PART_0_57'},
    18: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 128, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [17]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3a_branch2c_59_fuse_multiply_60_fuse_add_bn3a_branch2c_PART_0_61'},
    19: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 512, 'D': 1, 'OY': 28, 'OX': 28},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [15], 'Y': [18]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res3a_62'},
    20: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 512, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [19]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3b_branch2a_64_fuse_multiply_65_fuse_add_bn3b_branch2a_PART_0_66'},
    21: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 128, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [20]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3b_branch2b_68_fuse_multiply_69_fuse_add_bn3b_branch2b_PART_0_70'},
    22: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 128, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [21]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3b_branch2c_72_fuse_multiply_73_fuse_add_bn3b_branch2c_PART_0_74'},
    23: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 512, 'D': 1, 'OY': 28, 'OX': 28},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [19], 'Y': [22]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res3b_75'},
    24: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 512, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [23]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3c_branch2a_77_fuse_multiply_78_fuse_add_bn3c_branch2a_PART_0_79'},
    25: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 128, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [24]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3c_branch2b_81_fuse_multiply_82_fuse_add_bn3c_branch2b_PART_0_83'},
    26: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 128, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [25]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3c_branch2c_85_fuse_multiply_86_fuse_add_bn3c_branch2c_PART_0_87'},
    27: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 512, 'D': 1, 'OY': 28, 'OX': 28},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [23], 'Y': [26]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res3c_88'},
    28: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 512, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [27]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3d_branch2a_90_fuse_multiply_91_fuse_add_bn3d_branch2a_PART_0_92'},
    29: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 128, 'C': 128, 'OY': 28, 'OX': 28, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [28]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3d_branch2b_94_fuse_multiply_95_fuse_add_bn3d_branch2b_PART_0_96'},
    30: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 128, 'OY': 28, 'OX': 28, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [29]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res3d_branch2c_98_fuse_multiply_99_fuse_add_bn3d_branch2c_PART_0_100'},
    31: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 512, 'D': 1, 'OY': 28, 'OX': 28},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [27], 'Y': [30]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res3d_101'},
    32: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1024, 'C': 512, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [31]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4a_branch1_103_fuse_multiply_104_fuse_add_bn4a_branch1_PART_0_105'},
    33: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 512, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [31]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4a_branch2a_106_fuse_multiply_107_fuse_add_bn4a_branch2a_PART_0_108'},
    34: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [33]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4a_branch2b_110_fuse_multiply_111_fuse_add_bn4a_branch2b_PART_0_112'},
    35: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1024, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [34]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4a_branch2c_114_fuse_multiply_115_fuse_add_bn4a_branch2c_PART_0_116'},
    36: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 1024, 'D': 1, 'OY': 14, 'OX': 14},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [32], 'Y': [35]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res4a_117'},
    37: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 1024, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [36]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4b_branch2a_119_fuse_multiply_120_fuse_add_bn4b_branch2a_PART_0_121'},
    38: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [37]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4b_branch2b_123_fuse_multiply_124_fuse_add_bn4b_branch2b_PART_0_125'},
    39: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1024, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [38]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4b_branch2c_127_fuse_multiply_128_fuse_add_bn4b_branch2c_PART_0_129'},
    40: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 1024, 'D': 1, 'OY': 14, 'OX': 14},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [36], 'Y': [39]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res4b_130'},
    41: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 1024, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [40]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4c_branch2a_132_fuse_multiply_133_fuse_add_bn4c_branch2a_PART_0_134'},
    42: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [41]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4c_branch2b_136_fuse_multiply_137_fuse_add_bn4c_branch2b_PART_0_138'},
    43: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1024, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [42]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4c_branch2c_140_fuse_multiply_141_fuse_add_bn4c_branch2c_PART_0_142'},
    44: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 1024, 'D': 1, 'OY': 14, 'OX': 14},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [40], 'Y': [43]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res4c_143'},
    45: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 1024, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [44]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4d_branch2a_145_fuse_multiply_146_fuse_add_bn4d_branch2a_PART_0_147'},
    46: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [45]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4d_branch2b_149_fuse_multiply_150_fuse_add_bn4d_branch2b_PART_0_151'},
    47: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1024, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [46]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4d_branch2c_153_fuse_multiply_154_fuse_add_bn4d_branch2c_PART_0_155'},
    48: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 1024, 'D': 1, 'OY': 14, 'OX': 14},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [44], 'Y': [47]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res4d_156'},
    49: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 1024, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [48]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4e_branch2a_158_fuse_multiply_159_fuse_add_bn4e_branch2a_PART_0_160'},
    50: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [49]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4e_branch2b_162_fuse_multiply_163_fuse_add_bn4e_branch2b_PART_0_164'},
    51: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1024, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [50]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4e_branch2c_166_fuse_multiply_167_fuse_add_bn4e_branch2c_PART_0_168'},
    52: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 1024, 'D': 1, 'OY': 14, 'OX': 14},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [48], 'Y': [51]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res4e_169'},
    53: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 1024, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [52]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4f_branch2a_171_fuse_multiply_172_fuse_add_bn4f_branch2a_PART_0_173'},
    54: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 256, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [53]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4f_branch2b_175_fuse_multiply_176_fuse_add_bn4f_branch2b_PART_0_177'},
    55: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1024, 'C': 256, 'OY': 14, 'OX': 14, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [54]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res4f_branch2c_179_fuse_multiply_180_fuse_add_bn4f_branch2c_PART_0_181'},
    56: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 1024, 'D': 1, 'OY': 14, 'OX': 14},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [52], 'Y': [55]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res4f_182'},
    57: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 2048, 'C': 1024, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [56]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res5a_branch1_184_fuse_multiply_185_fuse_add_bn5a_branch1_PART_0_186'},
    58: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 1024, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [56]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res5a_branch2a_187_fuse_multiply_188_fuse_add_bn5a_branch2a_PART_0_189'},
    59: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 512, 'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [58]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res5a_branch2b_191_fuse_multiply_192_fuse_add_bn5a_branch2b_PART_0_193'},
    60: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 2048, 'C': 512, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [59]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res5a_branch2c_195_fuse_multiply_196_fuse_add_bn5a_branch2c_PART_0_197'},
    61: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 2048, 'D': 1, 'OY': 7, 'OX': 7},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [57], 'Y': [60]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res5a_198'},
    62: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 2048, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [61]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res5b_branch2a_200_fuse_multiply_201_fuse_add_bn5b_branch2a_PART_0_202'},
    63: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 512, 'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [62]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res5b_branch2b_204_fuse_multiply_205_fuse_add_bn5b_branch2b_PART_0_206'},
    64: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 2048, 'C': 512, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [63]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res5b_branch2c_208_fuse_multiply_209_fuse_add_bn5b_branch2c_PART_0_210'},
    65: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 2048, 'D': 1, 'OY': 7, 'OX': 7},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [61], 'Y': [64]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res5b_211'},
    66: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 2048, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [65]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res5c_branch2a_213_fuse_multiply_214_fuse_add_bn5c_branch2a_PART_0_215'},
    67: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 512, 'C': 512, 'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [66]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res5c_branch2b_217_fuse_multiply_218_fuse_add_bn5c_branch2b_PART_0_219'},
    68: {   'operator_type': 'Conv',
            'equation': 'O[b][k][oy][ox]+=W[k][c]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 2048, 'C': 512, 'OY': 7, 'OX': 7, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [67]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('OX', 2), 'D4': ('OY', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'conv2d_res5c_branch2c_221_fuse_multiply_222_fuse_add_bn5c_branch2c_PART_0_223'},
    69: {   'operator_type': 'Add',
            'equation_relations': [],
            'loop_dim_size': {'B': 1, 'G': 2048, 'D': 1, 'OY': 7, 'OX': 7},
            'equation': 'O[b][g][d][oy][ox]=X[g][oy][ox]+Y[g][oy][ox]',
            'operand_source': {'X': [65], 'Y': [68]},
            'constant_operands': [],
            'operand_precision': {'O': 32, 'O_final': 8, 'X': 8, 'Y': 8},
            'memory_operand_links': {'O': 'O', 'X': 'I1', 'Y': 'I1'},
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'name': 'add_res5c_224'},
    70: {   'operator_type': 'Pool',
            'equation': 'O[b][g][oy][ox]+=W[fx][fy]*I[b][g][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'G': 2048, 'OY': 1, 'OX': 1, 'FY': 7, 'FX': 7},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 0, 'I': 8},
            'operand_source': {'W': [], 'I': [69]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('G', 8)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'avg_pool2d_pool5_226'},
    71: {   'operator_type': 'Dense',
            'equation': 'O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][ix][iy]',
            'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
            'loop_dim_size': {'B': 1, 'K': 1000, 'C': 2048, 'OY': 1, 'OX': 1, 'FY': 1, 'FX': 1},
            'operand_precision': {'O': 32, 'O_final': 8, 'W': 8, 'I': 8},
            'operand_source': {'W': [], 'I': [70]},
            'constant_operands': ['W'],
            'core_allocation': 1,
            'spatial_mapping': {'D1': ('K', 8), 'D2': ('C', 32), 'D3': ('B', 2), 'D4': ('B', 2)},
            'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'},
            'name': 'dense_fc1000_Gemm_PART_0_228_fuse_add_fc1000_Gemm_229'}}
